name: "Tests"

on: [pull_request]
jobs:
  lint:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Setup Docker
      run: docker compose up -d --build --wait

    - name: Run Unit Tests
      run: docker compose exec web vendor/bin/phpunit --configuration phpunit.xml --testsuite unit

    - name: Run FPM E2E Tests
      run: docker compose exec web vendor/bin/phpunit --configuration phpunit.xml --testsuite fpm

    - name: Run Swoole E2E Tests
      run: docker compose exec web vendor/bin/phpunit --configuration phpunit.xml --testsuite swoole
